### ISSUE TITLE
Free Gigalixir db doesn't support uuid-ossp extension

### ISSUE THREAD

**Issue by tmock12** [tmock12/taylor_mock#4]
Welp, I wanted to use uuid's as primary IDs via:

```elixir
config :taylor_mock,
       TaylorMock.Repo,
       migration_primary_key: [
         name: :id,
         type: :binary_id,
         autogenerate: false,
         read_after_writes: true,
         default: {:fragment, "uuid_generate_v4()"}
       ]
```

and 

```elixir
  @primary_key {:id, :binary_id, autogenerate: false, read_after_writes: true}
  @foreign_key_type :binary_id
  schema ...
```

but.. when I went to add the extension, `execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"", "")`, I found out the free tier on Gigalixir doesn't allow you to add PG extentions 🤦 . 

So documenting this here for future reference if I decide to move off Gigalixir and re-type my id columns. 

See [changes in branch as example](https://github.com/tmock12/taylor_mock/tree/tmock12/uuid-no-worky-on-free-gigalixir)

**Comment by jesseshieh** [comment]
@tmock12 sorry about that. The standard tier definitely supports that extension if you're willing to upgrade. If you like, I can give you some credits to test it out. Just let me know if there's anything I can do to help.

**Comment by tmock12** [comment]
@jesseshieh No worries! I'll end up paying for it to support the project. This is my personal site and code playground but I wanted to give Gigalixir a try. So far it's been great. This issue was more to document my work in case I want to go back. Not really a true "issue" as I would never expect anything extra from a free tier. Thanks for all your work on Gigalixir ❤️
